app:
  numberOfProducts: 10
  customers: 10

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: objects_mapper
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS objects_mapper

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
